### ISSUE TITLE
Deployed instance of EtherToken

### ISSUE THREAD

**Issue by jordanschalm** [gnosis/gnosis-contracts#47]
Hello, I am looking to make use of the Gnosis [EtherToken](https://github.com/gnosis/gnosis-contracts/blob/master/contracts/Tokens/EtherToken.sol). I happened across this [deployed Wrapped Ether contract](https://etherscan.io/address/0xecf8f87f810ecf450940c9f60066b4a7a501d6a7#code) that seems like it is pretty heavily used. Unfortunately it has no link to its source code. I'm wondering if you are able to verify that this is an instance of the Gnosis EtherToken implementation, or maybe point me in the direction of what other implementation it might be if you happen to have an idea?

**Comment by cag** [comment]
I don't believe it is an instance of the Gnosis EtherToken. It was not deployed directly onto the chain, but rather via a contract, suggesting that it is likely created by a factory contract. Since we have not written a factory for the EtherToken, in order for it to be the Gnosis EtherToken, somebody would have had to have written a corresponding factory contract.

On that note, the name tag `WrappedETH-MKR` seems to suggest that it is from MakerDAO. I have not figured out exactly what though, and the only other ERC20 ether wrapper I am aware of comes from Zeppelin, but they are not particularly difficult to write. I would be curious to know what you come up with!

Closing, but feel free to add more if something comes up.
